const blogData = [
    {
      id: 1,
      title: "Exploring the Great Outdoors",
      image: "/images/mountain.jpg",
      publishDate: "2023-09-25",
      author: "Adventurer Alice",
      description: "Discover the beauty of nature on a hiking expedition.",
      content: "Hiking is an incredible way to connect with nature...",
    },
    {
      id: 2,
      title: "A Culinary Journey: Tasting the World's Flavors",
      image: "/images/food.jpg",
      publishDate: "2023-09-26",
      author: "Foodie Frank",
      description: "Embark on a global culinary adventure with us.",
      content: "Traveling around the world and trying different cuisines...",
    },
    {
      id: 3,
      title: "Tech Trends of the Future",
      image: "/images/tech.jpg",
      publishDate: "2023-09-27",
      author: "Tech Enthusiast Tina",
      description: "Stay ahead of the curve with these tech predictions.",
      content: "The tech world is constantly evolving, and it's important to...",
    },
    {
      id: 4,
      title: "Artistic Expression: Exploring Contemporary Art",
      image: "/images/art.jpg",
      publishDate: "2023-09-28",
      author: "Art Aficionado Alex",
      description: "Delve into the world of contemporary art and creativity.",
      content: "Contemporary art is a vibrant and diverse field that...",
    },
    {
      id: 5,
      title: "Healthy Living: Mind, Body, and Soul",
      image: "/images/health.jpg",
      publishDate: "2023-09-29",
      author: "Wellness Warrior Wendy",
      description: "Discover holistic wellness practices for a better life.",
      content: "Living a healthy life encompasses more than just physical fitness...",
    },
    {
      id: 6,
      title: "The Wonders of Astronomy",
      image: "/images/astronomy.jpg",
      publishDate: "2023-09-30",
      author: "Stargazer Steve",
      description: "Explore the mysteries of the universe and beyond.",
      content: "Astronomy is an ancient science that continues to captivate...",
    },
    {
      id: 7,
      title: "Travel Tales: Adventures Around the Globe",
      image: "/images/travel.jpg",
      publishDate: "2023-10-01",
      author: "Globe-trotter Grace",
      description: "Join us on a journey to discover incredible destinations.",
      content: "Traveling is an exhilarating experience that broadens our horizons...",
    },
    {
      id: 8,
      title: "The World of Literature: Book Reviews and More",
      image: "/images/books.jpg",
      publishDate: "2023-10-02",
      author: "Bookworm Ben",
      description: "Dive into the pages of captivating books and stories.",
      content: "Books have the power to transport us to different worlds and...",
    },
    {
      id: 9,
      title: "Music Mania: Exploring Diverse Melodies",
      image: "/images/music.jpg",
      publishDate: "2023-10-03",
      author: "Melody Maven Mia",
      description: "Celebrate the magic of music in all its forms.",
      content: "Music is a universal language that resonates with people...",
    },
    {
      id: 10,
      title: "Gaming Galore: A World of Virtual Adventures",
      image: "/images/gaming.jpg",
      publishDate: "2023-10-04",
      author: "Gamer George",
      description: "Enter the realm of gaming and embark on epic quests.",
      content: "Video games offer a unique form of interactive entertainment...",
    },
    // Add more blog post objects here
  ];
  
  export default blogData;
  